 name: Deploy website on push

 on:
  push:
    branches:
      - main

 jobs:
  web-deploy:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Test FTP Connection
        run: nc -vz ftp.inncapel.com 21

      - name: Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: "ftp"
